# Largely taken from black's workflow at 
# https://github.com/psf/black/blob/main/.github/workflows/upload_binary.yml

name: Publish agent

on:
  release:
    types: [published]

permissions:
  contents: write # actions/upload-release-asset needs this.

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
        include:
          - os: windows-2019
            pathsep: ";"
            asset_name: agent.exe
            executable_mime: "application/vnd.microsoft.portable-executable"

    steps:
      - uses: actions/checkout@v4

      - name: Set up latest Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.4"

      - name: Install dependencies and PyInstaller
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install .
          python -m pip install pyinstaller

      - name: Build executable with PyInstaller
        run: >
          pyinstaller -F --name ${{ matrix.asset_name }} src/akf_windows/server/__init__.py

      - name: Upload binary as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/${{ matrix.asset_name }}
          asset_name: ${{ matrix.asset_name }}
          asset_content_type: ${{ matrix.executable_mime }}